config/routes.rb
Sample::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'

  match '/signup',     to: 'users#new',             via: 'get'
  match '/signin',     to: 'sessions#new',          via: 'get'
  match '/signout',    to: 'sessions#destroy',      via: 'delete'
  
  match '/help',       to: 'static_pages#help',     via: 'get'
  match '/about',      to: 'static_pages#about',    via: 'get'
  match '/contact',    to: 'static_pages#contact',  via: 'get'
  match '/community',  to: 'static_pages#community',  via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_secure_password

  before_save { email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# -*- encoding : utf-8 -*-
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Комбинация адреса электронной почты и пароля не подходит'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
# -*- encoding : utf-8 -*-
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Добро пожаловать в Chesshall"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

    
  private

	  def user_params
	      params.require(:user).permit(:name, :email, :password,
	                                   :password_confirmation)
	  end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper

	def full_title(page_title)
		base_title = "Chesshall"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
	remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
  
end

app/helpers/static_pages_helper.rb
# -*- encoding : utf-8 -*-
module StaticPagesHelper
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
	def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.chesshall.com">Chesshall</a>
    by NoName Company
  </small>
  <nav>
    <ul>
      <li><%= link_to "О нас",   about_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to image_tag("Chesshall.png", alt: "Chesshall"), root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-center">
					<li><%= link_to "Игровой зал", '#' %></li>
					<li><%= link_to "Турнирный зал", '#' %></li>
					<li><%= link_to "Учебный зал", '#' %></li>
					<li><%= link_to "Читальный зал", '#' %></li>
				</ul>
				<ul class="nav pull-right">
					<% if signed_in? %>
			            <li><%= link_to "Users", users_path %></li>
			            	<div class="btn-group">
							  <%= link_to current_user.name, current_user, class: "btn" %>
							  <button data-toggle="dropdown" class="btn dropdown-toggle"><span class="caret"></span></button>
							    <ul class="dropdown-menu pull-right">
					                <li><%= link_to "Мои сообщества", '#' %></li>
					                <li><%= link_to "Мои турниры", '#' %></li>
					                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
					                <li class="divider"></li>
					                <li>
					                  <%= link_to "Выйти", signout_path, method: "delete" %>
					                </li>
				              </ul>
							</div>		            
			          <% else %>
							<li><%= link_to "Войти", signin_path %></li>
			          <% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_navigation.html.erb
<navigation>
	<div>
		<ul class="nav nav-pills nav-stacked">
			<li><%= link_to "Мои сообщества", '#' %></li>
			<li><%= link_to "Мои турниры", '#' %></li>
			<li><%= link_to "Настройки", '#' %></li>
		</ul>
	</div>
</navigation>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
	  <link href="/wp-content/themes/clear-theme/styles/bootstrap.css" rel="stylesheet">
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>

	<body style="background-color: whitesmoke">
<!-- 		<%= render 'layouts/header' %> -->
		<div class="container-fluid" style="padding: 60px 40px 20px 40px; min-width: 380px">
			<% flash.each do |key, value| %>
	       		<div class="alert alert-<%= key %>"><%= value %></div>
	      	<% end %>
			<%= yield %>
<!-- 			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %> -->
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "Ошибка") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About')%>

<h1>About Us</h1>
<p>
	<a href="http://www.chesshall.com">Chesshall</a>. Мы сделали онлайн-шахматы удобными.
</p>

app/views/static_pages/chesscircles.html.erb
<% provide(:title, 'Chess circles')%>

<h1>For chess circles and tournament organizers</h1>
<p>
	Теперь проводить турниры с любой системой жеребьевки стало как никогда проще.
</p>


app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>

<h1>Help</h1>
<p>Обращайтесь!</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <%= image_tag("ChessHallLarge.png", alt: "ChessHall") %>
  <h2>Шахматы объединяют людей со всего мира.</h2>
  <h2>Здесь мы стремимся сделать игру комфортнее.</h2>
  <div class="center" style="margin-top: 100px">
	<h3>
    	Следите за обновлениями:
	</h3>
	<p>
		<%= link_to image_tag("Twitter-Logo_50.png", alt: "Twitter", :class => 'img-logo'), 'http://twitter.com/chesshall' %>
		<%= link_to image_tag("FB-Logo_50.png", alt: "Facebook", :class => 'img-logo'), 'http://www.facebook.com/chesshallcom' %>
		<%= link_to image_tag("VK-Logo_50.png", alt: "Vkontakte", :class => 'img-logo'), 'http://vk.com/chesshall' %>
	</p>
  </div>
</div>

<!-- <div class="row-fluid rowfluidwidth CHborderStyleUp">
	<div class="span3">
		<div class= "center ">
		<h2>Chesshall</h2>
			<p>
			Добро пожаловать в шахматный холл! Но так-как сайт пока не работает, почитай о нас тут <a href="http://chesshall.atlassian.net">Atlassian</a>
			</p>
			<%= link_to "Присоединиться!", signup_path, class: "btn btn-large btn-primary" %>
		</div>
	</div>
	<div class="span3 CHsquarestyle">
		<div class= "center ">
		<h2>Игрокам</h2>
			<p>
			Загрзуите приложение для Windows
			</p>
			<%= link_to "Скачать", "#", class: "btn btn-large btn-primary" %>
		</div>
	</div>
	<div class="span6" style="height: max">
	<div class= "center ">
		<h2>Шахматным секциям</h2>
			<p>
			Создайте страницу вашего шахматного клуба. Размещайте фотографии. Проводите и сохраняйте все турниры в одном месте.
			</p>
	</div>
	</div>
</div>
<div class="row-fluid rowfluidwidth CHborderStyleDown">
	<div class="span3 CHsquarestyle">
		<div class= "center ">
		<h2>Организаторам турниров и судьям</h2>
			<p>
			Проводите жеребьевку турнира онлайн.
			</p>
		</div>
	</div>
	<div class="span3">
	</div>
	<div class="span6 CHsquarestyle">
	</div>
</div>
 -->

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Редактирование профиля") %>
<h1>Редактирование профиля</h1>

<div class="row">
	<div class="span6">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name, "Имя пользователя" %>
		    <%= f.text_field :name %>

		    <%= f.label :email, "Адрес электронной почты" %>
		    <%= f.text_field :email %>

		    <%= f.label :password, "Пароль" %>
		    <%= f.password_field :password %>

		    <%= f.label :password_confirmation, "Подтверждение пароля" %>
		    <%= f.password_field :password_confirmation %>

		    <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
		<% end %>
		
		<%= gravatar_for @user %>
   		<a href="http://gravatar.com/emails">Изменить</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Регистрация</h1>

<div class="row">
	<div class="span6 offset10">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name, "Имя пользователя" %>
			<%= f.text_field :name %>

			<%= f.label :email, "Адрес электронной почты" %>
			<%= f.text_field :email %>

			<%= f.label :password, "Пароль" %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Подтверждение пароля" %>
			<%= f.password_field :password_confirmation %>
	
			<%= f.submit "Присоединиться", class: "btn btn-large btn-primery" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for@user %>
				<%= @user.name %>
			</h1>
		</section>
		<%= render 'layouts/navigation' %>
	</aside>
</div>